### ISSUE TITLE
Save and Quit Maps

### ISSUE THREAD

**Issue by ojinsingapore** [TIBasic/dot-dash-ti#4]
Pressing the "MODE" (or other button, although MODE is the same as QUIT) does not quit MapMaker.

**Comment by Mcthecuber** [comment]
So, what's happening, is that once you press the QUIT button, it stores "Quitting" into string1. The next time the loop executes, the loop should see that the string has "Quitting" inside it, and should stop. However, there was a value for the variable G stored last time the loop executed, and therefore, string one is reassigned to whatever thing the G menu sets it too. To fix, you could use a do while loop, or you could store and check another string instead

**Comment by ojinsingapore** [comment]
Wow. You're smart. I'll change the code.
